name: Build and mark state as success
'on':
  push: 
    branches: 
      - develop
      - feature/*

jobs:
  test:  
    runs-on: windows-latest
    steps:
      - name: Echo
        run:
          echo Hello!

